"""Adiciona situacao_cadastral a estabelecimentos

Revision ID: 1443f49ea403
Revises: 368b62e6ee04
Create Date: 2025-08-18 10:45:51.158129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1443f49ea403'
down_revision: Union[str, Sequence[str], None] = '368b62e6ee04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('situacao_cadastral', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'situacao_cadastral')
    # ### end Alembic commands ###
