"""Adiciona nome_fantasia e data_inicio a estabelecimentos

Revision ID: 1f54ad039489
Revises: 21b885d55a2a
Create Date: 2025-08-18 11:36:44.913952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f54ad039489'
down_revision: Union[str, Sequence[str], None] = '21b885d55a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('nome_fantasia', sa.String(), nullable=True))
    op.add_column('estabelecimentos', sa.Column('data_inicio_atividade', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'data_inicio_atividade')
    op.drop_column('estabelecimentos', 'nome_fantasia')
    # ### end Alembic commands ###
