"""Adiciona situacao_cadastral a estabelecimentos

Revision ID: 21b885d55a2a
Revises: 1443f49ea403
Create Date: 2025-08-18 10:46:46.802308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b885d55a2a'
down_revision: Union[str, Sequence[str], None] = '1443f49ea403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
