"""Adiciona tabela de estabelecimentos

Revision ID: 368b62e6ee04
Revises: c574ab1b0679
Create Date: 2025-08-17 13:36:38.980981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368b62e6ee04'
down_revision: Union[str, Sequence[str], None] = 'c574ab1b0679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('cnpj_completo', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimentos_cnpj_completo'), 'estabelecimentos', ['cnpj_completo'], unique=True)
    op.create_index(op.f('ix_estabelecimentos_id'), 'estabelecimentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estabelecimentos_id'), table_name='estabelecimentos')
    op.drop_index(op.f('ix_estabelecimentos_cnpj_completo'), table_name='estabelecimentos')
    op.drop_table('estabelecimentos')
    # ### end Alembic commands ###
