"""Adiciona nome_fantasia e data_inicio a estabelecimentos

Revision ID: e29cd7a793e6
Revises: 1f54ad039489
Create Date: 2025-08-18 11:37:24.947748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29cd7a793e6'
down_revision: Union[str, Sequence[str], None] = '1f54ad039489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
