"""Cria tabelas iniciais

Revision ID: e65ef05c6b89
Revises: 
Create Date: 2025-08-15 16:13:51.146870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65ef05c6b89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('porte', sa.String(length=2), nullable=True),
    sa.Column('optante_simples', sa.Boolean(), nullable=True),
    sa.Column('optante_mei', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('declaracoes_pgdas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.String(length=6), nullable=False),
    sa.Column('valor_declarado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_iss_apurado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_transmissao', sa.Date(), nullable=True),
    sa.Column('retificadora', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaracoes_pgdas_competencia'), 'declaracoes_pgdas', ['competencia'], unique=False)
    op.create_index(op.f('ix_declaracoes_pgdas_id'), 'declaracoes_pgdas', ['id'], unique=False)
    op.create_table('pagamentos_daf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.String(length=6), nullable=False),
    sa.Column('data_arrecadacao', sa.Date(), nullable=False),
    sa.Column('valor_principal_iss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_multa_iss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_juros_iss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_daf_competencia'), 'pagamentos_daf', ['competencia'], unique=False)
    op.create_index(op.f('ix_pagamentos_daf_id'), 'pagamentos_daf', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_daf_id'), table_name='pagamentos_daf')
    op.drop_index(op.f('ix_pagamentos_daf_competencia'), table_name='pagamentos_daf')
    op.drop_table('pagamentos_daf')
    op.drop_index(op.f('ix_declaracoes_pgdas_id'), table_name='declaracoes_pgdas')
    op.drop_index(op.f('ix_declaracoes_pgdas_competencia'), table_name='declaracoes_pgdas')
    op.drop_table('declaracoes_pgdas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
